/*
* This file is auto-generated by gen-weights.py
*/

#pragma once
#include <stdio.h>
#include <stdint.h>

#define IMG_ROWS 28
#define IMG_COLS 28


// CONV layer
#define KRN_ROWS	3
#define KRN_COLS	3
#define KRN_FILTERS	32
#define	PAD_ROWS (KRN_ROWS - 1)
#define	PAD_COLS (KRN_COLS - 1)

// Pool layer.
#define POOL_SIZE 2
